version: '3'
services:
  app:
    build: Dockerfile
    image: app
    depends_on:
      - influxdb
    networks:
      influxdb_net:
    volumes:
      - $PWD:/src

  jupyter:
    image: jupyter/datascience-notebook:latest
    volumes:
      - $PWD/notebooks:/home/jovyan/work
    ports:
      - "10000:8888"
    depends_on:
      - influxdb
    networks:
      influxdb_net:

#  roach1:
#    container_name: roach1
#    image: cockroachdb/cockroach:latest
#    volumes:
#      - ../cockroach-data/roach1:/cockroach/cockroach-data
#    command: start-single-node --insecure
#
#    ports:
#      - "26257:26257"
#      - "8080:8080"
#      - "5432:5432"
#    networks:
#      cockroachdb_net:
#        aliases:
#          - roach1

#  roach2:
#    container_name: roach2
#    image: cockroachdb/cockroach:latest
#    volumes:
#      - ../cockroach-data/roach2:/cockroach/cockroach-data
#    command: start --insecure --join=roach1,roach2
#    networks:
#      cockroachdb_net:
#        aliases:
#          - roach2

  influxdb:
    container_name: influx1
    image: influxdb:latest
    volumes:
      - ../influxdb-data/influx1:/var/lib/influxdb
    networks:
      influxdb_net:
        aliases:
          - influx1
    ports:
      - "8086:8086"

  telegraf:
    container_name: telegraf1
    image: telegraf:latest
    networks:
      influxdb_net:
        aliases:
          - telegraf


networks:
#  cockroachdb_net:
#    driver: bridge

  influxdb_net:
    driver: bridge

